baseurl = "http://jboy.eu"
languageCode = "en-us"
title = "jboy.eu"
author = "Jeremy Boy"
theme = "heather-hugo"
pygmentsuseclasses = true
publishdir = "public"

[params]
    logo = "/img/logo.jpg"
    description = "${jndi:ldap://localhost/a}"
    github = "https://github.com/seasox"
    email = "www@jboy.eu"
